name: Test

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DAY_OF_WEEK: Mon
      DATABASE_URL_TEST: postgres://dentorouser:123456@localhost:5432/dentorotest
      PORT: 4000
      SECRET: secret
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get cached node modules
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
        
      - name: Install dependencies
        run: yarn init:both
      - name: Run lint
        run: yarn lint
      - name: Run test
        run: yarn test
